<?php
namespace Database\Seeders;
use App\Models\{Organization,Category,Venue,Seat,Event,Show};
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
class CinemaSeeder extends Seeder {
 public function run(): void {
  $org=Organization::create(['name'=>'سینماپلاس','slug'=>'cinemaplus','phone'=>'02191000000','email'=>'info@cinemaplus.test']);
  $cats=[]; foreach([['فیلم','film'],['تئاتر','theater'],['کودک و خانواده','family'],['کمدی','comedy'],['درام','drama'],['کنسرت خوانندگان','singer-concerts']] as [$name,$slug]) $cats[$slug]=Category::create(['name'=>$name,'slug'=>$slug,'type'=>'event']);
  $venues=[]; foreach([['پردیس ملت','تهران','خیابان ولیعصر'],['سینما آزادی','تهران','میدان انقلاب'],['تالار وحدت','تهران','میدان وحدت']] as [$name,$city,$address]){$v=Venue::create(['organization_id'=>$org->id,'name'=>$name,'city'=>$city,'address'=>$address,'capacity'=>96]); for($row=0;$row<8;$row++)for($num=1;$num<=12;$num++)Seat::create(['venue_id'=>$v->id,'row_label'=>chr(1575+$row),'number'=>$num,'type'=>$row===0?'vip':'standard']);$venues[]=$v;}
  $events=[['در آغوش خاک','درامی درباره انتخاب‌های سخت و امید','drama','آرمان رضایی'],['شهر بی‌خواب','روایتی اجتماعی از یک شب پرماجرا','drama','سارا نادری'],['ماه کوچک','انیمیشن خانوادگی برای همه سنین','family','مریم کاظمی'],['آخرین مرز','ماجراجویی در جست‌وجوی حقیقت','drama','کیان فرهمند'],['عشق اتفاقی','کمدی عاشقانه شهری','comedy','نوید شریفی'],['پرده آخر','قصه‌ای درباره صحنه و زندگی','drama','لیلا موسوی'],['پروازهای خاموش','درامی انسانی درباره مهاجرت','drama','امیرحسین یزدان'],['رویای آبی','داستانی خانوادگی از شروع دوباره','family','نگار توکلی'],['ساعت شنی','تریلر معمایی در یک شب بارانی','drama','پارسا نیک‌نام'],['کافه باران','کمدی گرم درباره دو دوست قدیمی','comedy','سینا راد'],['خط روشن','درامی امیدبخش درباره یک انتخاب','drama','مهتاب احمدی'],['خانه شماره هفت','رازهای یک خانه قدیمی','drama','فرهاد اکبری'],['یک روز معمولی','کمدی اجتماعی درباره زندگی روزمره','comedy','پویا مرادی'],['ستاره شمالی','ماجراجویی خانوادگی برای تمام سنین','family','الهام کریمی'],['نیمه شب تهران','روایتی شهری از چند آدم غریبه','drama','رضا حاتمی'],['قصه‌های مادربزرگ','انیمیشن ایرانی برای کودکان','family','هانیه صادقی'],['مسیر برگشت','درامی درباره خانواده و بخشش','drama','بهرام کاوه'],['صدای باران','درامی شاعرانه و موسیقایی','drama','ترانه نوری'],['روزهای طلایی','کمدی عاشقانه در یک شرکت شلوغ','comedy','علی اکبری'],['سینمای فردا','مستندی درباره آینده هنر و فناوری','drama','مهدی بهرامی']];
  $images=['home-concept.png','seat-selection-concept.png','admin-dashboard-concept.png']; foreach($events as $i=>[$title,$summary,$cat,$director]){$e=Event::create(['organization_id'=>$org->id,'category_id'=>$cats[$cat]->id,'title'=>$title,'slug'=>Str::slug($title).'-'.$i,'summary'=>$summary,'description'=>'داستان کامل، عوامل، اطلاعات نمایش و تجربه تماشای این اثر در سینماپلاس.','director'=>$director,'cast'=>'بازیگر اول، بازیگر دوم، بازیگر مهمان','country'=>'ایران','language'=>'فارسی','type'=>'cinema','duration'=>90+($i%5)*15,'age_rating'=>$i%2?'+۱۲':'همه سنین','is_featured'=>$i<6,'status'=>'published']);foreach(array_unique([$images[$i%3],$images[($i+1)%3]]) as $index=>$asset){$image=public_path('images/concepts/'.$asset);if(is_file($image))$e->addMedia($image)->preservingOriginal()->toMediaCollection($index===0?'poster':'gallery');} for($day=0;$day<7;$day++)Show::create(['event_id'=>$e->id,'venue_id'=>$venues[$i%3]->id,'starts_at'=>now()->addDays($day)->setTime(14+($i%5),30),'ends_at'=>now()->addDays($day)->setTime(16+($i%5),20),'price'=>220000,'vip_price'=>420000]);}
  $first=Event::where('slug','در-آغوش-خاک-0')->first();$poster=public_path('images/posters/dar-aghoosh-khak.png');if($first&&is_file($poster))$first->addMedia($poster)->preservingOriginal()->toMediaCollection('poster');$second=Event::where('slug','شهر-بی‌خواب-1')->first();$poster2=public_path('images/posters/shahr-bikhab.png');if($second&&is_file($poster2))$second->addMedia($poster2)->preservingOriginal()->toMediaCollection('poster');
  foreach(['مدیر سیستم','مدیر فروش','اپراتور گیشه','مشتری'] as $name) \Spatie\Permission\Models\Role::firstOrCreate(['name'=>$name,'guard_name'=>'web']);
 }
}
