<?php
namespace Tests\Feature;
use App\Models\{Organization,Venue,Seat,Event,Show,User,Order,Ticket,Reservation,OrganizationBooking};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Queue;
use Spatie\Permission\Models\Role;
use App\Jobs\SendSmsJob;
use Tests\TestCase;
class SecurityAndBookingTest extends TestCase
{
 use RefreshDatabase;
 private function show():Show{$org=Organization::create(['name'=>'Test','slug'=>'test']);$venue=Venue::create(['organization_id'=>$org->id,'name'=>'سالن تست','city'=>'تهران','capacity'=>1]);$seat=Seat::create(['venue_id'=>$venue->id,'row_label'=>'الف','number'=>1,'type'=>'standard']);$event=Event::create(['organization_id'=>$org->id,'title'=>'اثر تست','slug'=>'test-event','type'=>'cinema','status'=>'published']);return Show::create(['event_id'=>$event->id,'venue_id'=>$venue->id,'starts_at'=>now()->addDay(),'price'=>1000,'status'=>'on_sale']);}
 public function test_account_api_requires_sanctum_token():void{$this->getJson('/api/account/orders')->assertUnauthorized();}
 public function test_qr_requires_authenticated_owner_or_operator():void{$show=$this->show();$user=User::factory()->create();$order=Order::create(['user_id'=>$user->id,'show_id'=>$show->id,'code'=>'QR-TEST','total'=>1000,'status'=>'paid']);$ticket=Ticket::create(['order_id'=>$order->id,'seat_id'=>$show->venue->seats->first()->id,'code'=>'T-QR-TEST','status'=>'valid']);$this->get(route('tickets.qr',$ticket))->assertRedirect(route('login'));}
 public function test_second_reservation_is_rejected():void{$show=$this->show();$user=User::factory()->create();$this->actingAs($user)->post(route('booking.checkout',$show),['seats'=>[$show->venue->seats->first()->id]])->assertRedirect();$this->actingAs($user)->post(route('booking.checkout',$show),['seats'=>[$show->venue->seats->first()->id]])->assertStatus(409);$this->assertDatabaseCount('reservations',1);}
 public function test_customer_otp_dispatches_notification_job():void{Queue::fake();$this->post(route('customer.login.send'),['phone'=>'09120000000'])->assertSessionHas('success');Queue::assertPushed(SendSmsJob::class,fn($job)=>$job->phone==='09120000000');$this->assertDatabaseHas('login_codes',['phone'=>'09120000000']);}
 public function test_mobile_checkout_creates_paid_order_ticket_and_sms_job():void{Queue::fake();$show=$this->show();$user=User::factory()->create(['phone'=>'09121111111']);$response=$this->actingAs($user,'sanctum')->postJson('/api/shows/'.$show->id.'/checkout',['seats'=>[$show->venue->seats->first()->id]]);$response->assertCreated()->assertJsonPath('status','paid');$this->assertDatabaseHas('orders',['user_id'=>$user->id,'status'=>'paid']);$this->assertDatabaseHas('tickets',['status'=>'valid']);Queue::assertPushed(SendSmsJob::class,fn($job)=>$job->phone==='09121111111');}
 public function test_health_endpoint_reports_database_and_cache():void{$this->getJson('/health')->assertOk()->assertJsonPath('status','ok')->assertJsonPath('checks.database','ok')->assertJsonPath('checks.cache','ok');}
 public function test_organization_booking_is_created_for_authenticated_customer():void{$show=$this->show();$user=User::factory()->create();$this->actingAs($user)->post(route('organization-bookings.store',$show),['organization_name'=>'سازمان نمونه','contact_name'=>'مدیر خرید','phone'=>'09120000000','email'=>'buy@example.test','guest_count'=>80,'kind'=>'seminar','notes'=>'رزرو سالن برای سمینار'])->assertRedirect(route('organization-bookings.success'));$this->assertDatabaseHas('organization_bookings',['show_id'=>$show->id,'user_id'=>$user->id,'kind'=>'seminar','status'=>'pending']);}
 public function test_api_checkin_requires_operator_role():void{$show=$this->show();$owner=User::factory()->create();$ticket=Ticket::create(['order_id'=>Order::create(['user_id'=>$owner->id,'show_id'=>$show->id,'code'=>'CI-TEST','total'=>1000,'status'=>'paid'])->id,'seat_id'=>$show->venue->seats->first()->id,'code'=>'T-CI-TEST','status'=>'valid']);$operator=User::factory()->create();$this->actingAs($operator,'sanctum')->postJson('/api/tickets/'.$ticket->id.'/checkin')->assertForbidden();$role=Role::create(['name'=>'اپراتور گیشه','guard_name'=>'web']);$operator->assignRole($role);$this->actingAs($operator,'sanctum')->postJson('/api/tickets/'.$ticket->id.'/checkin')->assertOk()->assertJsonPath('ok',true);$this->assertDatabaseHas('tickets',['id'=>$ticket->id,'status'=>'used']);}
}
